version: '3'

services: 
  app:
    build: 
      context: ./node
    image: isabellasantos/app
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 30s node index.js
    networks: 
      - node-nginx
    tty: true
    depends_on: 
      - db
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes: 
      - ./mysql:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - node-nginx
  nginx:
    build: 
      context: ./nginx
    image: isabellasantos/nginx
    container_name: nginx
    tty: true
    networks: 
      - node-nginx
    ports: 
      - "8080:80"
    depends_on: 
      - app

networks: 
  node-nginx:
    driver: bridge  